import type { Metadata } from "next";
import { Inter, Roboto_Mono } from "next/font/google";
import { getCurrentUser, logout } from "./lib/auth";
import "./globals.css";

const geistSans = Inter({ variable: "--font-geist-sans", subsets: ["latin"] });

const geistMono = Roboto_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <header className="border-b bg-white dark:bg-black">
          <nav className="mx-auto flex max-w-5xl items-center justify-between px-6 py-4">
            <a href="/" className="text-xl font-semibold">ScriptHub</a>
            <div className="flex items-center gap-6">
              <a href="/browse" className="text-sm">Browse</a>
              <a href="/upload" className="text-sm">Upload</a>
              <AuthNav />
            </div>
          </nav>
        </header>
        <main>{children}</main>
        <footer className="mx-auto max-w-5xl px-6 py-8 text-xs text-zinc-500">
          Powered by Rscripts.net
        </footer>
      </body>
    </html>
  );
}

async function AuthNav() {
  const user = await getCurrentUser();
  async function doLogout() {
    "use server";
    await logout();
  }
  if (!user) return <a href="/login" className="text-sm">Login</a>;
  return (
    <div className="flex items-center gap-4">
      {user.role === "admin" && <a href="/moderation" className="text-sm">Moderation</a>}
      <span className="text-sm text-zinc-500">{user.username}</span>
      <form action={doLogout}>
        <button className="text-sm underline">Logout</button>
      </form>
    </div>
  );
}
